### ISSUE TITLE
docs: use `nomodule` for polyfill

### ISSUE THREAD

**Issue by lukeed** [rdmurphy/scroller#51]
Should probably be using `<script nomodule src="//polyfill.io/...">` within `/docs` and in the README text.

This allows modern browsers to skip the check in most cases ([IO](https://caniuse.com/intersectionobserver) vs [script[type=module]](https://caniuse.com/es6-module)). Even though the Polyfill.io service sends down an empty empty if/when `IntersectionObserver` is supported, it's still a request and a script to deal with.

**Comment by rdmurphy** [comment]
Agreed! Changes made.
